# Generated by Django 5.2.10 on 2026-04-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wau', '0002_projectimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/gallery/'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='projects/gallery/videos/'),
        ),
    ]
