# Generated by Django 5.2.13 on 2026-04-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wau', '0004_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_media_type',
            field=models.CharField(default='image', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='cover_public_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='cover_secure_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
