# Generated by Django 5.2.10 on 2026-04-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wau', '0004_project_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_media_type',
            field=models.CharField(blank=True, default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='cover_media_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='media_type',
            field=models.CharField(blank=True, default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='media_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
