# Generated by Django 5.2.13 on 2026-04-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wau', '0005_project_cover_media_type_project_cover_public_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='cover_public_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='cover_secure_url',
        ),
        migrations.AddField(
            model_name='projectimage',
            name='image_type',
            field=models.CharField(choices=[('gallery', 'Gallery'), ('before', 'Before')], default='gallery', max_length=20),
        ),
    ]
