# Generated by Django 5.2.13 on 2026-04-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wau', '0006_remove_project_cover_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image_type',
            field=models.CharField(choices=[('gallery', 'Gallery'), ('before', 'Before'), ('after', 'After')], default='gallery', max_length=20),
        ),
    ]
