# Generated by Django 5.2.13 on 2026-04-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wau', '0007_alter_projectimage_image_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('summary', models.TextField(max_length=320)),
                ('content', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image_type',
            field=models.CharField(choices=[('image', 'Image'), ('gallery', 'Gallery'), ('before', 'Before'), ('after', 'After')], db_column='media_type', default='image', max_length=20),
        ),
    ]
