# Generated by Django 5.2.13 on 2026-04-22 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wau', '0008_newspost_alter_projectimage_image_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sector', models.CharField(choices=[('agriculture', 'Agriculture'), ('renewable_energy', 'Renewable Energy'), ('infrastructure', 'Infrastructure'), ('technology', 'Technology'), ('manufacturing', 'Manufacturing'), ('tourism', 'Tourism'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('financial_services', 'Financial Services'), ('other', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the investment opportunity')),
                ('capex_min', models.DecimalField(decimal_places=2, help_text='Minimum capital required (USD)', max_digits=15)),
                ('capex_max', models.DecimalField(decimal_places=2, help_text='Maximum capital sought (USD)', max_digits=15)),
                ('expected_roi', models.DecimalField(decimal_places=2, help_text='Expected ROI percentage', max_digits=5)),
                ('timeline_months', models.IntegerField(help_text='Expected project timeline in months')),
                ('target_sectors', models.CharField(blank=True, help_text='Comma-separated target sectors or industries', max_length=500)),
                ('key_benefits', models.TextField(blank=True, help_text='Key benefits and highlights')),
                ('risk_assessment', models.TextField(blank=True, help_text='Risk factors and mitigation strategies')),
                ('featured', models.BooleanField(default=False, help_text='Show on investment page hero section')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-featured', '-published_at', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='newspost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='InvestmentInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('investment_range', models.CharField(blank=True, help_text='Indicated capital range (e.g., "1M-5M")', max_length=50)),
                ('message', models.TextField(help_text='Inquiry message or additional questions')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='wau.investmentopportunity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
